<a href="https://colab.research.google.com/github/SaurabhChakravorty/Bark-at-your-own-risk/blob/master/Word_Embedding_Keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Word Embedding Techniques using Layers in Keras

In [13]:
#tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [14]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [15]:
### Vocabulary size
voc_size=10000

#### One Hot representation

In [16]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[3707, 3656, 6446, 2655], [3707, 3656, 6446, 6647], [3707, 5873, 6446, 5513], [3869, 3413, 6467, 5655, 792], [3869, 3413, 6467, 5655, 3991], [3072, 3707, 262, 6446, 1756], [9511, 4374, 3977, 5655]]


### Word embedding representation

In [5]:
import numpy as np
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [6]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3707 3656 6446 2655]
 [   0    0    0    0 3707 3656 6446 6647]
 [   0    0    0    0 3707 5873 6446 5513]
 [   0    0    0 3869 3413 6467 5655  792]
 [   0    0    0 3869 3413 6467 5655 3991]
 [   0    0    0 3072 3707  262 6446 1756]
 [   0    0    0    0 9511 4374 3977 5655]]


In [7]:
dim = 10
### Vocabulary size
voc_size=10000

In [8]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [9]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [10]:
print(model.predict(embedded_docs))

[[[ 0.03780823 -0.00356252 -0.0163995  -0.0465259  -0.02695894
    0.0382187   0.04409096  0.04683626  0.00661765 -0.00957085]
  [ 0.03780823 -0.00356252 -0.0163995  -0.0465259  -0.02695894
    0.0382187   0.04409096  0.04683626  0.00661765 -0.00957085]
  [ 0.03780823 -0.00356252 -0.0163995  -0.0465259  -0.02695894
    0.0382187   0.04409096  0.04683626  0.00661765 -0.00957085]
  [ 0.03780823 -0.00356252 -0.0163995  -0.0465259  -0.02695894
    0.0382187   0.04409096  0.04683626  0.00661765 -0.00957085]
  [-0.03485673 -0.03105202 -0.01493488  0.00704194 -0.01237786
    0.01272618 -0.03158294  0.04405953 -0.0380267  -0.01037236]
  [-0.02903642  0.00047232  0.04157121 -0.03607861 -0.01962605
    0.02124992  0.01764731 -0.00588393  0.00215334 -0.00815661]
  [ 0.01233177  0.02768233 -0.00490887  0.01307939 -0.04186841
    0.0270786  -0.04545518  0.03742533  0.03641467  0.0154461 ]
  [ 0.02707911  0.02735777  0.00103049  0.03098092 -0.04190136
   -0.02253739  0.00294326 -0.01101439 -0.003218

In [11]:
embedded_docs[0]

array([   0,    0,    0,    0, 3707, 3656, 6446, 2655], dtype=int32)

In [12]:
print(model.predict(embedded_docs)[0])

[[ 0.03780823 -0.00356252 -0.0163995  -0.0465259  -0.02695894  0.0382187
   0.04409096  0.04683626  0.00661765 -0.00957085]
 [ 0.03780823 -0.00356252 -0.0163995  -0.0465259  -0.02695894  0.0382187
   0.04409096  0.04683626  0.00661765 -0.00957085]
 [ 0.03780823 -0.00356252 -0.0163995  -0.0465259  -0.02695894  0.0382187
   0.04409096  0.04683626  0.00661765 -0.00957085]
 [ 0.03780823 -0.00356252 -0.0163995  -0.0465259  -0.02695894  0.0382187
   0.04409096  0.04683626  0.00661765 -0.00957085]
 [-0.03485673 -0.03105202 -0.01493488  0.00704194 -0.01237786  0.01272618
  -0.03158294  0.04405953 -0.0380267  -0.01037236]
 [-0.02903642  0.00047232  0.04157121 -0.03607861 -0.01962605  0.02124992
   0.01764731 -0.00588393  0.00215334 -0.00815661]
 [ 0.01233177  0.02768233 -0.00490887  0.01307939 -0.04186841  0.0270786
  -0.04545518  0.03742533  0.03641467  0.0154461 ]
 [ 0.02707911  0.02735777  0.00103049  0.03098092 -0.04190136 -0.02253739
   0.00294326 -0.01101439 -0.00321881 -0.03132162]]
